trigger:
- master

pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\azagent\_work\1\s\projects\mdb-ui-kit'
    ArtifactName: 'AngKit'
    publishLocation: 'Container'