trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build 
  displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: 'ls $(System.DefaultworkingDIrectory)/dist/mdb-angular-ui-kit-free'